baseURL = 'https://timot05.github.io/'
languageCode = 'en-us'
title = 'SARK'
canonifyurls = true

# Novela settings
theme = "hugo-theme-novela"

[pagination]
pagerSize = 6

[params]
[social]
# twitter= ""
# github= ""
# linkedin= ""
# instagram = "#"
# dribbble = "#"
# youtube = "#"

[taxonomies]
author = "authors"
