baseURL = 'https://timot05.github.io/public/'
languageCode = 'en-us'
title = 'SARK'
canonifyurls = true

# Novela settings
theme = "hugo-theme-novela"

paginate = 6

[social]
# twitter= ""
# github= ""
# linkedin= ""
# instagram = "#"
# dribbble = "#"
# youtube = "#"

[taxonomies]
author = "authors"
